### ISSUE TITLE
Language specific URL slugs

### ISSUE THREAD

**Issue by MartinaFarkasova** [Kentico/cloud-sample-app-xamarin#2]
We have a new feature, language-specific URL slugs. Consider if the sample app needs to be updated.

See the task in JIRA: https://kentico.atlassian.net/browse/DEL-1635

**Comment by petrsvihlik** [comment]
We have a .NET sample here: https://github.com/Kentico/cloud-sample-app-net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+1669
